version: '3.8'

services:
  database:
    container_name: database_sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=100_SQLServer
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql
    expose:
      - 1433
    ports:
      - 1433:1433

volumes:
  sqlserver_data: